# The Docker image that will be used to build your app
image: python:3.8-buster
# Functions that should be executed before the build script is run
before_script:
  - pip install -r requirements/prod.txt
pages:
  script:
    - export TZ="Asia/Seoul"
    - echo $NAVER_API_KEY > naverapi.key
    - python main.py
    - mv pages public
    - date
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
